[package]
name = "snek"
version = "0.1.0"
authors = ["rufus-stone <60827786+rufus-stone@users.noreply.github.com>"]
edition = "2018"

[dependencies]
snek_core = { path = "../libs/snek_core" }
snek_ai = { path = "../libs/snek_ai" }
