[package]
name = "mandelbrot"
version = "1.0.0"
authors = ["rufus-stone <60827786+rufus-stone@users.noreply.github.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.22"
num = "0.4.0"
image = "0.23.14"
